image: codeclou/docker-atlassian-sdk:sdk-6.3.10
 
pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - cd server-side-rendering
          - atlas-version
          - atlas-mvn clean install
          - cd ../client-side-rendering
          - atlas-mvn clean install